### ISSUE TITLE
How to activate the adapter on windows?

### ISSUE THREAD

**Issue by HuRui-1026** [bneumann/CppUTest-Test-Adapter#3]
Exciting to find this extension!
But how to use it on windows? There is not  a command to call the test.

**Comment by bneumann** [comment]
Sorry for the delay.
I found the bug it was kinda stupid. If you don't set the CWD I prepend a "/" which is not working under windows (also under linux but no one cared ;) )
Going to fix it

**Comment by bneumann** [comment]
PR #5 should fix the issue. Will do a release on azure in the next days

**Comment by bneumann** [comment]
Version 0.1.15 is out now
