### ISSUE TITLE
Make it possible to specify objdump path

### ISSUE THREAD

**Issue by spoorcc** [bneumann/CppUTest-Test-Adapter#33]
Currently the extension uses `objdump` from `PATH` to find the location of a test when double clicking.

I would like to use a specific `objdump`. Would it be possible to add a new setting `cpputestExplorer.objDumpPath` to specify this?
Or is there a way I'm overlooking?

(Thanks for your work 👍 )

**Comment by bneumann** [comment]
Hi, that is certainly possible. Thanks for the issue :)

**Comment by spoorcc** [comment]
Thanks!!
