### ISSUE TITLE
adapter do not find any testcases

### ISSUE THREAD

**Issue by Dubi09** [bneumann/CppUTest-Test-Adapter#38]
Hello, 
I am trying to use this extension on windows for our tests. Unfortunately I am can't discover any testcases from the executables. The test windows is blank. without any entry.

I looked how you discover tests and all the used which you use for the executable should give desired output.

Could You give me a hint how to fix it?

Thank you very much.

**Comment by Dubi09** [comment]
This problem is fixed in pre-released version 1.0.6.

**Comment by bneumann** [comment]
okay then, let's get it out 👯

**Comment by bneumann** [comment]
1.0.8 is out! I had some problems with vsce again. Hopefully getting a automatic release system soon
