### ISSUE TITLE
Is there a way to start the Debugger?

### ISSUE THREAD

**Issue by lokimon** [bneumann/CppUTest-Test-Adapter#4]
Just wondering if it would be possible to add a "Debug" option as well as the "Run" option.

Thanks!

**Comment by bneumann** [comment]
Yeah I tried to get it running but it somehow refused to show the correct lines and files. I'll look into it.

**Comment by bneumann** [comment]
Good news it was easier than I thougt: 740b784
I will brush up the code and have it available soon

**Comment by lokimon** [comment]
That's awesome!
Can't wait to try it out.

**Comment by bneumann** [comment]
PR #5 should fix the issue. Will do a release on azure in the next days

**Comment by bneumann** [comment]
Version 0.1.15 is out now

**Comment by lokimon** [comment]
Works great!  Appreciate the timeliness on this.  The team will enjoy it.
