### ISSUE TITLE
How to use autorun

### ISSUE THREAD

**Issue by dabell-cc** [bneumann/CppUTest-Test-Adapter#41]
Hi there,
Less of an issue report, more of a question.

I see an option to enable autorun in the testing options menu, but aside from adding a small 'play' triangle on each test's icon I don't see an effect. Is this implemented? What should happen?
![image](https://user-images.githubusercontent.com/8835326/197005559-54ec57a0-3f43-4594-b8e7-5b8a9143fd1f.png)

Cheers!

**Comment by bneumann** [comment]
Hey mate, nope I never implemented it. I started adding a file watcher but I think the branch is pretty stale by now

**Comment by dabell-cc** [comment]
Explains why I don't see a change. Thanks for the rapid response!
