### ISSUE TITLE
Set the launch profile when debugging tests

### ISSUE THREAD

**Issue by alastairtree** [bneumann/CppUTest-Test-Adapter#47]
Is it possible to configure which configuration is opened from the launch.json when you try and debug a unit test? Seems like currently it just opens the first one?

**Comment by bneumann** [comment]
That's true, sorry bout that. I will look into it after my vacation.

**Comment by alastairtree** [comment]
@bneumann I have added PR #48 which will fix this issue and allow the user to chose the name of the launch profile they want to use, and if unspecified fall back to the existing behaviour.

**Comment by bneumann** [comment]
Wonderful, thanks for the help. Unfortunately I cannot make release from where I am right now. Will do in Sunday when I come back.
which reminds me to finally finish the pipeline for automatic releases.
