### ISSUE TITLE
Click on test to go to source?

### ISSUE THREAD

**Issue by lokimon** [bneumann/CppUTest-Test-Adapter#9]
Love the Extension, working well for us.

Just wondering if it's possible to jump to source if we click on a test?

I saw this in the README
"Somehow line number and file information are not propagated to the Test Explorer. I am on it."

Is this not possible?
Thanks!

**Comment by bneumann** [comment]
Thanks a lot! You are my prime user ;)
I will look into it today. It's been a while since I wrote that an I have some new ideas how to figure it out.

**Comment by bneumann** [comment]
@lokimon are you using windows or linux? Because I found a way to make it work for linux. But windows is always a bit tedious because tools like grep and objdump are not available

**Comment by bneumann** [comment]
I added a branch for testing under d925808
